#!/usr/bin/perl -w
# $Id: //info.ravenbrook.com/project/mps/master/test/test/script/require#2 $
#
# require all the qa harness pl files
#
# should have no side effects, except for compiling some functions,
# and setting some base values of variables

require "version";
require "useful";
require "display";
require "logging";
require "compile";
require "headread";
require "runtest";
require "clib";

require "dirs";
require "platform";

require "optproc";
require "options";

require "init";

1;

