# example/scheme/Makefile -- Makefile for the MPS Scheme example
#
# $Id: //info.ravenbrook.com/project/mps/master/example/scheme/Makefile#1 $

scheme: scheme.c
	$(CC) -g3 -ansi -pedantic -Wall -Wno-extended-offsetof -o scheme -I ../../code scheme.c ../../code/mps.c
