#!/usr/bin/perl -w
# $Id: //info.ravenbrook.com/project/mps/master/test/test/script/commands/try#2 $
#
# run tests interactively (allows for user input, immediate results,
# &c, but doesn't give results in standard format)

print "The try command has been removed. Please use the run command instead.\n";


